### ISSUE TITLE
repo needs description

### ISSUE THREAD

**Issue by thraxil** [appsembler/web-test-avl#4]
Vanta requires that all Github repos have a description.

**Comment by AlenaKB** [comment]
@thraxil what should be added on top of the existing description?

**Comment by thraxil** [comment]
@AlenaKB Vanta reads from the repo description, not the README:

![screenshot-2021-07-16-111422](https://user-images.githubusercontent.com/7821/125932630-6e8f76f1-6c49-4389-82ee-7abe9021cc99.png)

**Comment by AlenaKB** [comment]
@thraxil the best attention to detail award goes to me. Gonna fix it now
